### ISSUE TITLE
Even when P1HOME is empty, the game still attempts to pull out a marble

### ISSUE THREAD

**Issue by durangogt** [durangogt/aggravation#1]
* Minor issue but should be looked into eventually, for now just don't click on the marbles in the home location when rolling a 1

**Comment by durangogt** [comment]
Here is the error when P1HOME has zero elements in it and a roll of 1 was rolled:

```
A roll of 1 has been rolled....manually
clicked on a board spot...
Traceback (most recent call last):
  File ".\aggravation.py", line 568, in <module>
    main()
  File ".\aggravation.py", line 278, in main
    P1marbles[len(P1HOME)] = P1END #keep track of P1marbles - since we pull out the last one in P1HOME, thats the index
TypeError: object of type 'NoneType' has no len()
```

**Comment by durangogt** [comment]
There are 3 references for when we assign a new value to P1marbles....
* Search for exact string of ---> P1marbles[  (which results in output below)
* OUTPUT:
   * P1marbles[len(P1HOME)] = P1END <-- check here if len(P1HOME) is not null or >= 0
   * P1marbles[P1marbles.index(oldLocation)] = P1END
* Add conditional checking to make sure 
*

**Comment by durangogt** [comment]
Here is the solution to this problem:
```
                    elif(p1StartOccuppied == False and waitingForInput == True): 
                        # check if the spot clicked on is a board spot or home spot (i.e. is P1END a # or integer)
                        if (BOARD_TEMPLATE[ tempP1END[1] ][ tempP1END[0] ] != SPOT and len(P1HOME) > 0): # this means the player clicked on a marble in the home spot and there is at least one marble there
                            P1HOME = removeFromHome(P1HOME)                          # remove one from home, doesn't matter which marble in home they clicked on - it will pull out the last one
                            drawPlayerBox(P1COLOR,P1START)                           # draw player on their start position
                            P1END = P1START                                          # set end of turn locator
                            P1marbles[len(P1HOME)] = P1END #keep track of P1marbles - since we pull out the last one in P1HOME, thats the index
                            print('P1marbles marble coords tracking: %s' % (P1marbles))
                            p1StartOccuppied = True
                            waitingForInput = False

                        elif (BOARD_TEMPLATE[ tempP1END[1] ][ tempP1END[0] ] == SPOT): # this means the player clicked on a marble not on the home position
                            if (isValidMove(moves,P1marbles,tempP1END) == True):
                                P1END = tempP1END
                                P1marbles,P1END = animatePlayerMove(moves,P1marbles,P1END,P1HOME)
                                waitingForInput = False
                            else:
                                print("Invalid move, marble already exists, can't jump your own marbles")
                                displayStatus(PLAYERROR_SURF, PLAYERROR_RECT)                                
                                print("DEBUG: Roll: %i  NumInHome: %i  Marbles: %s" % (moves,(len(P1HOME)),P1marbles))                                

                        elif (BOARD_TEMPLATE[ tempP1END[1] ][ tempP1END[0] ] != SPOT and len(P1HOME) == 0): 
                            # this means the player clicked on a position in the home base but no marbles exist TODO asset this further up instead of here
                            displayStatus(PLAYERROR2_SURF, PLAYERROR2_RECT)                                
                            print("DEBUG: Roll: %i  NumInHome: %i  Marbles: %s" % (moves,(len(P1HOME)),P1marbles))
```
